-- Local dev mirror of ../../contracts/db_schema.sql, translated to SQLite so the
-- mastery service can actually run and be tested without a live Postgres instance.
--
-- IMPORTANT: contracts/db_schema.sql (Postgres/Supabase) is still the single source of
-- truth for table SHAPES. Nothing here changes a column, a type's meaning, or a
-- constraint's intent -- it only substitutes SQLite-compatible syntax for Postgres
-- syntax that SQLite doesn't support:
--   uuid            -> text (uuids are generated as strings in application code)
--   gen_random_uuid -> not available in sqlite; app code generates the uuid instead
--   timestamptz     -> text (ISO-8601 strings, generated by application code)
--   jsonb           -> text (JSON-encoded strings; app code json.dumps/json.loads)
--   text[]          -> text (JSON-encoded array string, e.g. '["a","b"]')
--
-- When this points at real Supabase Postgres in production, use
-- contracts/db_schema.sql as-is -- the application code in db.py already speaks in
-- terms of plain Python values (str/list/dict) and would only need its thin
-- sqlite3-specific bits (JSON encode/decode of columns) swapped for asyncpg/psycopg
-- passing native uuid/jsonb/array types directly.

create table if not exists students (
    id            text primary key,
    display_name  text not null,
    grade         integer not null check (grade between 1 and 3),
    created_at    text not null
);

create table if not exists skills (
    id              text primary key,
    label           text not null,
    category        text not null,
    prerequisite_of text not null default '[]'  -- JSON-encoded array of skill ids
);

create table if not exists student_skill_mastery (
    student_id  text not null references students(id) on delete cascade,
    skill_id    text not null references skills(id),
    weight      real not null default 0.0 check (weight between 0.0 and 1.0),
    updated_at  text not null,
    primary key (student_id, skill_id)
);

create table if not exists sessions (
    id                  text primary key,
    student_id          text not null references students(id) on delete cascade,
    passage_id          text not null,
    started_at          text not null,
    ended_at            text,
    wcpm                real,
    accuracy            real,
    self_corrections    integer default 0,
    miscues             text not null default '[]',       -- JSON array
    comprehension       text not null default '[]',        -- JSON array
    pipeline_latency_ms text,
    session_recap       text,
    hints_delayed_count integer not null default 0,
    hints_delayed_self_corrected_count integer not null default 0
);

create index if not exists idx_sessions_student on sessions(student_id, started_at desc);
